### ISSUE TITLE
Mejoras para la app

### ISSUE THREAD

**Issue by playzzz** [LaQuay/TDTChannels-APP#1]
**A NIVEL ESTÉTICO**
- En la búsqueda y filtrado de canales, los canales no se ordenan por categoría.
- Cambiar el icono de la web (tdtchannels.com) por el isotipoWEB
- Que todos los elementos de la app tengan los mismos márgenes a derecha e izquierda.
- Añadir el icono adaptativo
- Mejorar la estética de la ventana de filtrado
- Que el recuadro de los filtros tenga el mismo redondeo en px que el recuadro e los canales

**A NIVEL TÉCNICO**
- Marcar las emisiones de YouTube como 'Emisión YouTube' y los canales que no tienen m3u8 o tienen emisión vía web como 'Emisión web'.
- Añadir opción para marcar/desmarcar todas las categorías en la ventana de filtrado
- Añadir notificación para las emisoras y que no se detenga la reproducción de la emisora cuando salgas de la ficha de la emisora
- Añadir soporte para Chromecast
- Añadir EPG
- Agregar alertas en el EPG (que te avise con una notificación cuando comience un programa que has marcado como favorito)
- Añadir modo PiP (Picture-in-Picture)
- Para pantallas 18:9/19:9/19.5:9 estaría bien poder hacer el movimiento de "pinza", como en Youtube, para adaptar la imagen del stream a los bordes de la pantalla

**Comment by baenac2002** [comment]
Integración con Google chromcast

**Comment by coryweed** [comment]
Debería de poder reproducirse desde dentro de la app sin tener que salirse

**Comment by LaQuay** [comment]
> Debería de poder reproducirse desde dentro de la app sin tener que salirse

Hola, eso ya se puede hacer. Desde la primera versión... Puedes explicar a qué te refieres? Gracias

**Comment by LaQuay** [comment]
Nota para mi: Cuando se reproduce un stream, hacer que no se vaya a inactividad el dispositivo

**Comment by baenac2002** [comment]
Para la integración con Chromecast he encontrado este link por si puede servir de ayuda:
https://codigofacilito.com/articulos/chromecast-android

**Comment by playzzz** [comment]
Material para la app: https://drive.google.com/folderview?id=1U8sHvhuFKR4_owUGMFO7YNhgs1FcEF41

**Comment by GerardoCG** [comment]
En la sección de filtros poner un check por cada categoría (en caso de que la categoría tenga más de una subcategoria, como por ejemplo Spain)

**Comment by arualR46** [comment]
Buenas, acabo de descubrir esta pedazo de app, está genial, en mi móvil funciona de 10 pero tengo una sugerencia que hacer para los desarrolladores 😉 en casa tengo un Android TV un Xiaomi boxS y la app no funciona, soy consciente que Android TV y Android de móvil no tienen nada que ver y por eso estaría genial una versión para android tv 

Gracias por el trabajo 👍

**Comment by osmanyce** [comment]
Hola, como sugerencia de usabilidad, al momento de filtrar las ciudades, deberían incluir un marcar o desmarcar todo.
Otra cosa es que al abrir los canales casi nunca me funciona el primer link, y esto me cierra el canal donde accedí, sería bueno que si no funciona un link te deje en la pantalla del canal para probar otro link.

**Comment by riudarenes** [comment]
Hola seria una gran mejora si se ludieran haver listas de canales favoritos o preferidos.

**Comment by jhairos** [comment]
Sería interesante que el player reproduzca en picture in picture sin salirse de fronte menú principal.

**Comment by wuniversales** [comment]
Necesito un tema oscuro, cada vez que abro la app por la noche, es como... Socorro!!!! Mis ojos!!!!

**Comment by LaQuay** [comment]
Hola! Dejo aquí lo que en un principio he solucionado. La release aún no la he hecho pública, pero pronto estará.

**A NIVEL ESTÉTICO**
- Actualizar el placeholder (tienes las dos opciones, elige la que te guste más)
- Actualizar el placeholder de la ficha del canal
- En canales como RT News o France24 en la app no aparece de que idioma es el stream, así como se indica si un stream es GEO o no ó si es HD o SD, en este caso no indica el idioma.
- Que el recuadro de la categoría (Generalistas' Autonómicas, etc) tenga los mismos píxeles de redondeo que los recuadros de los canales
- Eliminar el guión de las opciones de emisión GEO/HD/SD. (Emisión - HD -> Emisión HD)
- Quitar el logo de las pastillas de las opciones de emisión y centrar el texto
- Que el recuadro con el logo del canal su nombre y URL tenga los mismos márgenes que los demás elementos
- Implementar el modo oscuro

**A NIVEL TÉCNICO**
- Adaptar la app para Android TV

**Comment by LaQuay** [comment]
Estas 3 peticiones a nivel técnico también estarán:
- Añadir notificación para las emisoras y que no se detenga la reproducción de la emisora cuando salgas de la ficha de la emisora
- Cuando intentas reproducir una emisora en la que su stream esta en m3u la app crashea.
- El reproductor de la radio no reproduce los m3u
