### ISSUE TITLE
¿Este proyecto sigue vivo?

### ISSUE THREAD

**Issue by eliseo-juan** [LaQuay/TDTChannels-APP#13]
Soy desarrollador de Android y la mitad de las cosas que faltan las puedo hacer en una horita o así, pero necesito saber si sigue vivo.
Si es así, mañana me pongo con lo siguiente:
- Soporte para AndroidTV
- Soporte para Live Channels en Android TV
- Fixes

**Comment by LaQuay** [comment]
Hola! Claro que sigue vivo. Estaría perfecto lo que comentas. Últimamente tengo poco tiempo... Escríbeme por Telegram si necesitas más info! @LaQuay. 

Nos vemos!
