### ISSUE TITLE
No se mantiene la APP en segundo plano al escuchar la radio en android

### ISSUE THREAD

**Issue by sergialarconrecio** [LaQuay/TDTChannels-APP#20]
Hola Buenas.

Cuando escuchas la radio y quieres la APP en segundo plano la radio se para igual que cuando apagas la pantalla para no gastar batería se apaga la emisora y no puedes escuchar la radio en segundo plano con la pantalla apagarada

Saludos.

**Comment by LaQuay** [comment]
Hola! El modo oscuro está disponible en la versión no open source del proyecto.
La puedes encontrar en www.tdtchannels.com, botón Android.

Este repositorio únicamente se actualizará para que siga siendo compatible. Pero no recibirá mejoras. Así lo indico en la pantalla principal.

Saludos!
