### ISSUE TITLE
Añadir modo oscuro

### ISSUE THREAD

**Issue by moldahutal** [LaQuay/TDTChannels-APP#21]
El modo oscuro está muy de moda y yo lo uso en todas las aplicaciones que disponen de ella.
Me gustaría tenerla en esta aplicación también.

muchas gracias.

**Comment by LaQuay** [comment]
Hola! El modo oscuro está disponible en la versión no open source del proyecto.
La puedes encontrar en www.tdtchannels.com, botón Android.

Este repositorio únicamente se actualizará para que siga siendo compatible. Pero no recibirá mejoras. Así lo indico en la pantalla principal.

Saludos!
