### ISSUE TITLE
App crashea en tablet bq Aquaris m10 fhd

### ISSUE THREAD

**Issue by torbol** [LaQuay/TDTChannels-APP#3]
Hola, antes que nada me gustaría darte la enhorabuena por la pedazo de app, ojalá la sigas mejorando y dure mucho tiempo :P. 

Me ocurre que la estoy intentado instalar en una tablet bq Aquaris m10 fhd con android 6.0, instala bien pero cuando la abro me aparece un error que dice que la app se ha cerrado inesperadamente. ¿Que datos (logs) necesitarias para ver si se puede arreglar el fallo?

**Comment by LaQuay** [comment]
Hola @torbol 
Creo haber encontrado la solución a tu error. Pronto, si no hoy, sacaré una versión nueva. Te agradecería que lo probases :)

**Comment by LaQuay** [comment]
@torbol Puedes probar con la versión 0.5.0, debería estar solucionado 👍

**Comment by torbol** [comment]
Muchísimas gracias, ahora va perfecta!! 😁✌

**Comment by R0ci0-V3rd3al** [comment]
Hola @torbol trato de saber porque tu aplicación denota una detección por virustotal  llamada "PUP.HightConfidence". si es un falso positivó desde ya me agradaría saberlo.

**Comment by LaQuay** [comment]
> Muchísimas gracias!!, ahora va perfecta

Me alegro!



> Hola @LaQuay trato de saber porque tu aplicación denota una detección por virustotal llamada "PUP.HightConfidence". si es un falso positivó desde ya me agradaría saberlo.

Hola Rocío, para la próxima abre una Issue diferente por favor. Te respondo:

"Virus Total analiza los datos del Apk con su firma y su hash: si el Apk ya ha sido comprobado anteriormente te dará los datos del último análisis con los resultados. Dependiendo de los errores sabrás si la aplicación es o no segura. Aunque eso sí, puede haber algún **falso positivo**, como en el caso de la alerta «PUP.HighConfidence»: si solo uno de los 59 antivirus detectó algo raro eso no significa que el Apk tenga virus." https://elandroidelibre.elespanol.com/2018/03/verificar-apk-libres-virus.html

**Comment by R0ci0-V3rd3al** [comment]
Gracias. ahora va bien. ya no sale la detección
