### ISSUE TITLE
Cierre de aplicación en radio

### ISSUE THREAD

**Issue by hannibal1986** [LaQuay/TDTChannels-APP#6]
En xiaomi se cierra la app al intentar reproducir algunas radios

![Screenshot_2019-07-04-21-14-18-782_laquay com canalestdt](https://user-images.githubusercontent.com/19189665/60685352-f1323200-9ea2-11e9-84d4-3717094f2a8f.png)

**Comment by LaQuay** [comment]
Cierro, debería estar solucionado. Gracias!
