### ISSUE TITLE
v0.5.2 - 2019-07-16 - No instala la aplicacion "aplicacion no instalada"

### ISSUE THREAD

**Issue by acts268** [LaQuay/TDTChannels-APP#9]
Cuando intentas hacer la instalacion con el apk v0.5.2 - 2019-07-16 no termina de instalar la aplicación dice "aplicacion no instalada" probado en Android 6.0.1

**Comment by mOrfiUs** [comment]
v0.5.1 instalada y funcional 100%
v0.5.2 Aplicación no instalada.
tablet LG-V500/Android 6.01
CyanogenMod 13.0-20161107
Kernel 3.4.0.
Gracias por el desarrollo. Saludos.

**Comment by LaQuay** [comment]
Hola! Tomo nota. Pronto sacaré la 0.5.3, a ver si se soluciona.
Cabe decir que para tener instalada la 0.5.2 hay que borrar cualquier otra antes.

**Comment by malversan** [comment]
Estaba afrontando el mismo error al pasar de la versión 0.5.2 a la 0.5.4. Finalmente pude instalar la nueva desinstalando antes la versión antigua.

Conclusión: Para actualizar la aplicación a una nueva versión hay que desinstalar antes la versión antigua.
